CREATE OR REPLACE STORAGE INTEGRATION RETAIL_S3_INTEGRATION
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = 'S3'
    ENABLED = TRUE
    STORAGE_AWS_ROLE_ARN = '<AWS_IAM_ROLE_ARN>'
    STORAGE_ALLOWED_LOCATIONS = (
        's3://<S3_BUCKET>/raw/sales/'
    );

DESC INTEGRATION RETAIL_S3_INTEGRATION;
