USE DATABASE RETAIL_SALES_DB;
USE SCHEMA RAW;

CREATE OR REPLACE STAGE SALES_S3_STAGE
    URL = 's3://<S3_BUCKET>/raw/sales/'
    STORAGE_INTEGRATION = RETAIL_S3_INTEGRATION
    FILE_FORMAT = SALES_CSV_FORMAT;

LIST @SALES_S3_STAGE;
