USE DATABASE RETAIL_SALES_DB;
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS RAW_SALES (
    DATE        DATE,
    PRODUCT     VARCHAR(100),
    REGION      VARCHAR(50),
    UNITS_SOLD  NUMBER,
    UNIT_PRICE  NUMBER(10,2),
    SALES       NUMBER(12,2)
);
