USE DATABASE RETAIL_SALES_DB;
USE SCHEMA RAW;

COPY INTO RAW_SALES
FROM @SALES_S3_STAGE
FILE_FORMAT = (FORMAT_NAME = SALES_CSV_FORMAT)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
VALIDATION_MODE = 'RETURN_ERRORS';

COPY INTO RAW_SALES
FROM @SALES_S3_STAGE
FILE_FORMAT = (FORMAT_NAME = SALES_CSV_FORMAT)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'ABORT_STATEMENT';
