USE DATABASE RETAIL_SALES_DB;
USE SCHEMA RAW;

SELECT COUNT(*) AS TOTAL_RECORDS
FROM RAW_SALES;

SELECT *
FROM RAW_SALES
LIMIT 10;

SELECT
    SUM(IFF(DATE IS NULL, 1, 0))       AS DATE_NULLS,
    SUM(IFF(PRODUCT IS NULL, 1, 0))    AS PRODUCT_NULLS,
    SUM(IFF(REGION IS NULL, 1, 0))     AS REGION_NULLS,
    SUM(IFF(UNITS_SOLD IS NULL, 1, 0)) AS UNITS_SOLD_NULLS,
    SUM(IFF(UNIT_PRICE IS NULL, 1, 0)) AS UNIT_PRICE_NULLS,
    SUM(IFF(SALES IS NULL, 1, 0))      AS SALES_NULLS
FROM RAW_SALES;

SELECT *
FROM TABLE(
    INFORMATION_SCHEMA.COPY_HISTORY(
        TABLE_NAME => 'RAW_SALES',
        START_TIME => DATEADD('hour', -24, CURRENT_TIMESTAMP())
    )
)
ORDER BY LAST_LOAD_TIME DESC;
