USE DATABASE RETAIL_SALES_DB;

CREATE SCHEMA IF NOT EXISTS ANALYTICS;


CREATE OR REPLACE PROCEDURE ANALYTICS.RUN_RETAIL_SALES_PIPELINE()
RETURNS VARIANT
LANGUAGE PYTHON
RUNTIME_VERSION = '3.11'
PACKAGES = ('snowflake-snowpark-python')
HANDLER = 'retail_sales_pipeline.main'
IMPORTS = ('@RAW.SNOWPARK_CODE/retail_sales_pipeline.py')
EXECUTE AS OWNER;

